spring:
  datasource:
    url: jdbc:mysql:///wx-crud-practice
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: mysql
#    open-in-view: false

server:
  port: 9090
